# Generated by Django 4.2 on 2026-04-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='announcements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement_id', models.CharField(max_length=50)),
                ('event_id', models.CharField(max_length=10)),
                ('massage', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='assignments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('instructor_id', models.CharField(max_length=10)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('given_date', models.DateTimeField(blank=True, null=True)),
                ('assignment_id', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('sem', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=10)),
                ('sem', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.CharField(max_length=50)),
                ('dept_name', models.CharField(max_length=100)),
                ('hod', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Exams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_id', models.CharField(max_length=40)),
                ('course_id', models.CharField(max_length=30)),
                ('exam_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('max_score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor_id', models.CharField(max_length=10)),
                ('comments', models.CharField(max_length=50)),
                ('grade', models.CharField(max_length=10)),
                ('given_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('instructor_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=20)),
                ('mobileno', models.CharField(max_length=15, unique=True)),
                ('qualification', models.CharField(max_length=100)),
                ('experience', models.IntegerField()),
                ('joining_date', models.DateField()),
                ('department', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('sem', models.IntegerField()),
                ('sem1', models.IntegerField(default=models.IntegerField())),
                ('sem2', models.IntegerField(default=models.IntegerField())),
            ],
        ),
        migrations.CreateModel(
            name='newuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('mobileno', models.CharField(max_length=15, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_by', models.CharField(max_length=10)),
                ('message', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=100)),
                ('target', models.CharField(default='all', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='studentdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=40)),
                ('email_id', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=40)),
                ('sem', models.IntegerField()),
                ('year', models.IntegerField()),
                ('mobile_no', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='StudentExamScores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=40)),
                ('exam_id', models.CharField(max_length=30)),
                ('score', models.IntegerField()),
                ('performance_level', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('material_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=50)),
                ('semester', models.CharField(max_length=10)),
                ('instructor_name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='materials/')),
                ('upload_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
                ('instructor_id', models.CharField(max_length=10)),
                ('department', models.CharField(max_length=50)),
                ('enrolled_at', models.CharField(max_length=50)),
                ('sem', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='submissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Assignments_id', models.CharField(max_length=50)),
                ('Student_id', models.CharField(max_length=10)),
                ('file_url', models.FileField(upload_to='submissions/')),
                ('submitted_date', models.DateField()),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(max_length=50)),
                ('sem', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('day', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=50)),
                ('instructor_id', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='userlogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('utype', models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff'), ('student', 'Student')], max_length=20)),
            ],
        ),
    ]
