# Generated by Django 4.2 on 2026-04-24 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='sem1',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='sem2',
        ),
    ]
